### ISSUE TITLE
Pre trained model

### ISSUE THREAD

**Issue by startupgurukul** [X-rayLaser/keras-auto-hwr#1]
Hello Eugene,
Thank you for sharing. Do you mind providing a pre trained model for faster training and benchmarking

Thanks in advance

**Comment by X-rayLaser** [comment]
Hello @startupgurukul  and sorry for the late reply.

Yes, that's a good suggestion. I will start working on it as soon as I have time.

I assume that you want the model to recognize English handwriting.
In that case, the easiest way would be to train the model on IAM On-Line Handwriting Database.
Or do you have any particular dataset for training in mind?

**Comment by X-rayLaser** [comment]
Hi @startupgurukul. I have added a pre-trained model. It's stored in the weights/blstm directory.

**Comment by no-1ne** [comment]
Thank you
